name: Deploy to GitHub Pages

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout results
        uses: actions/checkout@v2
        with:
          ref: refs/heads/results
          path: results
      - name: Checkout speedlify
        uses: actions/checkout@v2
        with:
          path: default
      - name: Copy existing results
        run: cp -r results/. default/_data
      - name: Install npm dependencies
        run: npm install
        working-directory: default
      - name: Build speedlify
        run: |
          npm run build -- --pathprefix=${GITHUB_REPOSITORY#*/}
          npm run zip-results
        working-directory: default
      - name: Deploy to gh-pages branch
        run: |
          mkdir gh-pages
          cp -r default/_site/* gh-pages
          cd gh-pages
          ORIGIN=https://${{ github.repository_owner }}:${{ github.token }}@github.com/${{ github.repository }}.git
          git init
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b gh-pages
          git add .
          git commit -m "Deploy gh-pages"
          git push -uf $ORIGIN gh-pages
